"""m

Revision ID: cbb42eb63ebd
Revises: ed7112bb399d
Create Date: 2026-08-04 12:17:27.140945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cbb42eb63ebd"
down_revision: Union[str, Sequence[str], None] = "ed7112bb399d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("reviews_count", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "favorites", ["user_id", "book_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "favorites", type_="unique")
    op.drop_column("books", "reviews_count")
    # ### end Alembic commands ###
