"""

Revision ID: f38c8ba9cafd
Revises: cfd4c4e54d45
Create Date: 2026-07-24 21:05:39.035951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f38c8ba9cafd"
down_revision: Union[str, Sequence[str], None] = "cfd4c4e54d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books", "published_year", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("books", "cover_path", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("books", "file_path", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "file_path", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("books", "cover_path", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "books", "published_year", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
