"""add new BooksOrm

Revision ID: dcf5872de0ac
Revises: a85d6c83d27f
Create Date: 2026-07-24 20:52:28.400973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dcf5872de0ac"
down_revision: Union[str, Sequence[str], None] = "a85d6c83d27f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("published_year", sa.Integer(), nullable=False))
    op.add_column("books", sa.Column("average_rating", sa.Float(), nullable=False))
    op.add_column("books", sa.Column("cover_path", sa.String(), nullable=False))
    op.add_column("books", sa.Column("file_path", sa.String(), nullable=False))
    op.add_column(
        "books",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.drop_column("books", "rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("books", "created_at")
    op.drop_column("books", "file_path")
    op.drop_column("books", "cover_path")
    op.drop_column("books", "average_rating")
    op.drop_column("books", "published_year")
    # ### end Alembic commands ###
