"""

Revision ID: cfd4c4e54d45
Revises: dcf5872de0ac
Create Date: 2026-07-24 21:00:01.201774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cfd4c4e54d45"
down_revision: Union[str, Sequence[str], None] = "dcf5872de0ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "genre_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "genre_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
