"""add ReviewsOrm

Revision ID: 4df8f13c2164
Revises: f38c8ba9cafd
Create Date: 2026-07-25 08:12:05.725679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4df8f13c2164"
down_revision: Union[str, Sequence[str], None] = "f38c8ba9cafd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("rating", sa.Float(), nullable=False))
    op.add_column(
        "reviews",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "created_at")
    op.drop_column("reviews", "rating")
    # ### end Alembic commands ###
